// Generated by CoffeeScript 1.9.3
(function() {
  var cholesterol, healthy;

  cholesterol = 127;

  healthy = (200 > cholesterol && cholesterol > 60);

}).call(this);

//# sourceMappingURL=Chained Comparisons.js.map
