// Generated by CoffeeScript 1.9.3
(function() {
  var date, mood;

  if (singing) {
    mood = greatlyImproved;
  }

  if (happy && knowsIt) {
    clapsHands();
    chaChaCha();
  } else {
    showIt();
  }

  date = Friday ? sue : jill;

}).call(this);

//# sourceMappingURL=if, else, unless 和条件赋值.js.map
