// Generated by CoffeeScript 1.9.3
(function() {
  var error;

  try {
    allHellBreaksLoose();
    catsAndDogsLivingTogether();
  } catch (_error) {
    error = _error;
    print(error);
  } finally {
    clearUp();
  }

}).call(this);

//# sourceMappingURL=Try_Catch_Finally.js.map
