// Generated by CoffeeScript 1.9.3
(function() {
  var OPERATOR;

  OPERATOR = /^(?:[-=]>|[-+*\/%<>&|^!?=]=|>>>=?|([-+:])\1|([&|<>])\2=?|\?\.|\.{2,3})/;

}).call(this);

//# sourceMappingURL=块级的正则表达式.js.map
