// Generated by CoffeeScript 1.9.3
(function() {
  var author, html, mobyDick, quote, sentence;

  author = "Wittgenstein";

  quote = "A picture is a fact. -- " + author;

  sentence = (22 / 7) + " is a decent approximation of π";

  mobyDick = "Call me Ishmael. Some years ago -- never mind how long precisely -- having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world...";

  html = "<strong>\n  cup of coffeescript\n</strong>";

}).call(this);

//# sourceMappingURL=字符串替换, 块级的字符串, 块级的注释.js.map
