// Generated by CoffeeScript 1.9.3
(function() {
  var bitlist, kids, singers, song;

  song = ["do", "re", "mi", "fa", "so"];

  singers = {
    Jagger: "Rock",
    Elvis: "Roll"
  };

  bitlist = [1, 0, 1, 0, 0, 1, 1, 1, 0];

  kids = {
    brother: {
      name: "Max",
      age: 11
    },
    sister: {
      name: "Lucy",
      age: 12
    }
  };

  $('.account').attr({
    "class": 'active'
  });

  log(object["class"]);

}).call(this);

//# sourceMappingURL=对象和数组.js.map
