// Generated by CoffeeScript 1.9.3
(function() {
  var volume, winner;

  if (ignition === true) {
    launch();
  }

  if (band !== SpinalTap) {
    volume = 10;
  }

  if (answer !== nodeLinkFn) {
    letTheWildRumpusBegin();
  }

  if (car.speed < limit) {
    accelerate();
  }

  if (pick === 47 || pick === 92 || pick === 13) {
    winner = yws;
  }

  print(inspect("My name is " + this.name));

}).call(this);

//# sourceMappingURL=操作符和 aliase.js.map
