// Generated by CoffeeScript 1.9.3
(function() {
  var copy, end, middle, numbers, ref, start;

  numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9];

  start = numbers.slice(0, 3);

  middle = numbers.slice(3, -2);

  end = numbers.slice(-2);

  copy = numbers.slice(0);

  numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

  [].splice.apply(numbers, [3, 4].concat(ref = [-3, -4, -5, -6])), ref;

  console.log(numbers);

}).call(this);

//# sourceMappingURL=数组的切片和用 range 进行拼接.js.map
