// Generated by CoffeeScript 1.9.3
(function() {
  var Person, a, b, city, first, forecast, futurists, last, name, ref, ref1, ref2, ref3, ref4, street, temp, text, tim, weatherReport;

  a = 1;

  b = 2;

  ref = [b, a], a = ref[0], b = ref[1];

  weatherReport = function(location) {
    return [location, 72, "Mostly Sunny"];
  };

  ref1 = weatherReport("Berkeley, CA"), city = ref1[0], temp = ref1[1], forecast = ref1[2];

  futurists = {
    sculptor: "Umberto Boccioni",
    painter: "Vladimir Burliuk",
    poet: {
      name: "F.T. Marinetti",
      address: ["Via Roma 42R", "Bellagio, Italy 22021"]
    }
  };

  ref2 = futurists.poet, name = ref2.name, (ref3 = ref2.address, street = ref3[0], city = ref3[1]);


  /*tag = "<impossible>"
  
  [open, contents..., close] = tag.split("")
   */

  text = "Every literary critic believes he will outwit history and huave the last word";

  ref4 = text.split(" "), first = ref4[0], last = ref4[ref4.length - 1];

  Person = (function() {
    function Person(options) {
      this.name = options.name, this.age = options.age, this.length = options.length;
    }

    return Person;

  })();

  tim = new Person({
    age: 4
  });

}).call(this);

//# sourceMappingURL=解构赋值.js.map
