// Generated by CoffeeScript 1.9.3
(function() {
  var changeNumber, inner, outer;

  outer = 1;

  changeNumber = function() {
    var inner;
    inner = -1;
    return outer = 10;
  };

  inner = changeNumber();

}).call(this);

//# sourceMappingURL=词法作用域和变量安全.js.map
